// <auto-generated />
using System;
using ECommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApi.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20211121175825_ECommerce1233")]
    partial class ECommerce1233
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerceApi.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RegularPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Iphone_15_X",
                            Description = "Nice iphone 15 X PRO MAX",
                            DiscountedPrice = 790.5m,
                            Name = "Iphone 15",
                            RegularPrice = 890.5m
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Macbook_Pro",
                            Description = "It is nice macbook 1TB hdd",
                            DiscountedPrice = 4899.9m,
                            Name = "Macbook Pro",
                            RegularPrice = 5000m
                        },
                        new
                        {
                            Id = 3,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Oculus_Quest_2",
                            Description = "Oculus Quest 2 is our newest, most advanced all-in-one VR system yet.",
                            DiscountedPrice = 489.8m,
                            Name = "Oculus Quest 2",
                            RegularPrice = 550m
                        },
                        new
                        {
                            Id = 4,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Apple_Watch_7",
                            Description = "Apple Watch is het ultieme device voor een gezond leven. ",
                            DiscountedPrice = 749.9m,
                            Name = "Apple Watch 7",
                            RegularPrice = 800m
                        },
                        new
                        {
                            Id = 5,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Sony_Headset",
                            Description = "Buy Gaming headset?",
                            Name = "Sony Headset",
                            RegularPrice = 99.9m
                        });
                });

            modelBuilder.Entity("ECommerceApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anki@outlook.com",
                            FirstName = "Anki",
                            LastName = "De Jong",
                            Password = "1234",
                            Phone = "0617363601"
                        },
                        new
                        {
                            Id = 2,
                            Email = "dewitt@outlook.com",
                            FirstName = "Dewitt",
                            LastName = "Van de Berg",
                            Password = "1234",
                            Phone = "0655634616"
                        },
                        new
                        {
                            Id = 3,
                            Email = "dirck@outlook.com",
                            FirstName = "Dirck",
                            LastName = "Bakker",
                            Password = "1234",
                            Phone = "0621048961"
                        },
                        new
                        {
                            Id = 4,
                            Email = "gusta@outlook.com",
                            FirstName = "Gusta",
                            LastName = "Janssen",
                            Password = "1234",
                            Phone = "0687201108"
                        },
                        new
                        {
                            Id = 5,
                            Email = "gerritt@outlook.com",
                            FirstName = "Gerritt",
                            LastName = "Smit",
                            Password = "1234",
                            Phone = "0670902290"
                        },
                        new
                        {
                            Id = 6,
                            Email = "willem@outlook.com",
                            FirstName = "Willem",
                            LastName = "Meijer",
                            Password = "1234",
                            Phone = "0619116876"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
