// <auto-generated />
using System;
using ECommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApi.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20211113105746_CoverImageUrlAdded2")]
    partial class CoverImageUrlAdded2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerceApi.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RegularPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Product_1",
                            Description = "Developer",
                            DiscountedPrice = 2.5m,
                            Name = "Telefon",
                            RegularPrice = 5.5m
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Product_2",
                            Description = "Manager",
                            DiscountedPrice = 1.5m,
                            Name = "Tablet",
                            RegularPrice = 3.5m
                        },
                        new
                        {
                            Id = 3,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Product_3",
                            Description = "Kamyon",
                            DiscountedPrice = 1.5m,
                            Name = "Kamyon",
                            RegularPrice = 6.5m
                        },
                        new
                        {
                            Id = 4,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Product_4",
                            Description = "Dododo",
                            DiscountedPrice = 1.5m,
                            Name = "Laptop",
                            RegularPrice = 15.5m
                        },
                        new
                        {
                            Id = 5,
                            CoverImageUrl = "https://via.placeholder.com/335&text=Product_5",
                            Description = "Consultant",
                            DiscountedPrice = 3.5m,
                            Name = "Gemi",
                            RegularPrice = 33.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
